// The 1,000 most common passwords that are 8+ characters long (shorter ones
// already fail the length rule), lowercased, minus the one entry that spells
// out the age cutoff as a word: this list
// ships in the signup page's browser code, and that page never names the age
// cutoff (age-ui.test.tsx scans for it). 999 entries. Taken in order from SecLists
// Passwords/Common-Credentials/10k-most-common.txt (MIT licence,
// github.com/danielmiessler/SecLists). Data only; used by password-rule.ts.
export const COMMON_PASSWORDS: readonly string[] = [
  'password', '12345678', 'baseball', 'football', 'jennifer', 'superman', 'trustno1', 'michelle',
  'sunshine', '123456789', 'starwars', 'computer', 'corvette', 'princess', 'iloveyou', 'maverick',
  'samantha', 'steelers', 'whatever', 'hardcore', 'internet', 'mercedes', 'bigdaddy', 'midnight',
  '11111111', 'marlboro', 'victoria', 'butthead', 'startrek', 'liverpoo', 'danielle', 'redskins',
  'mountain', 'shithead', 'xxxxxxxx', '88888888', 'nicholas', 'metallic', 'qwertyui', 'dolphins',
  'cocacola', 'rush2112', 'jonathan', 'scorpion', 'asdfasdf', 'godzilla', 'williams', 'lifehack',
  'platinum', 'garfield', '69696969', 'jordan23', 'bullshit', 'airborne', 'elephant', 'explorer',
  'christin', 'december', 'benjamin', 'dickhead', 'brooklyn', 'redwings', 'michigan', '87654321',
  'guinness', 'einstein', 'snowball', 'alexande', 'passw0rd', 'lasvegas', 'slipknot', 'kimberly',
  '1q2w3e4r', 'carolina', 'colorado', 'creative', 'bollocks', 'darkness', 'asdfghjk', 'poohbear',
  'nintendo', 'november', 'password1', 'lacrosse', 'paradise', 'maryjane', 'spitfire', 'anderson',
  'cherokee', 'drowssap', 'marshall', '1qaz2wsx', 'caroline', 'franklin', 'snickers', 'courtney',
  'westside', 'patricia', 'semperfi', 'freeuser', 'babygirl', 'champion', 'softball', 'security',
  'wildcats', 'veronica', 'abcd1234', 'wolverin', 'remember', 'freepass', 'pearljam', 'mistress',
  'peekaboo', 'budlight', 'electric', 'stargate', 'brittany', 'swimming', 'scotland', 'swordfis',
  'blink182', 'virginia', 'passport', 'aaaaaaaa', 'rolltide', 'bulldogs', 'liverpool', 'chevelle',
  'mitchell', 'spiderma', 'patriots', 'cardinal', 'kawasaki', 'ncc1701d', 'airplane', 'scarface',
  'elizabet', 'wolfpack', 'lawrence', 'american', 'stingray', 'simpsons', 'srinivas', 'panthers',
  'pussycat', 'loverboy', 'tarheels', 'wolfgang', 'testtest', 'michael1', 'pakistan', 'infinity',
  'letmein1', 'hercules', 'billybob', 'pavilion', 'changeme', 'darkside', 'zeppelin', 'darkstar',
  'charlie1', 'wrangler', 'qwerty12', 'bobafett', 'business', 'sterling', 'babydoll', 'cheyenne',
  'longhorn', 'presario', 'mustang1', '21122112', 'q1w2e3r4', '12341234', 'devildog', 'bluebird',
  'metallica', 'access14', 'enterpri', 'blizzard', 'asdf1234', 'harrison', 'thailand', '1234567890',
  'cadillac', 'hellfire', 'lonewolf', '12121212', 'fireball', 'precious', 'engineer', 'basketba',
  'valentin', 'wetpussy', 'morpheus', 'hotstuff', 'fuck_inside', 'goldberg', 'wrinkle1', 'consumer',
  'serenity', '99999999', 'bigboobs', 'chocolat', 'christia', 'birthday', 'stephani', '1234qwer',
  '98765432', '77777777', 'highland', 'seminole', 'airforce', 'hamilton', 'buckeyes', 'abcdefgh',
  'goldfish', 'deftones', 'icecream', 'pleasure', 'juventus', 'ncc1701e', '51505150', 'cavalier',
  'aardvark', 'babylon5', 'savannah', 'yankees1', 'fredfred', 'concrete', 'shamrock', 'atlantis',
  'wordpass', 'predator', 'marathon', 'montreal', 'kathleen', 'jessica1', 'diamonds', 'stallion',
  'letmein2', 'clitoris', 'sundance', 'renegade', 'hollywoo', 'hello123', 'sweetpea', 'stocking',
  'campbell', 'christop', 'rockstar', 'geronimo', 'chandler', 'lovelove', 'greenday', '987654321',
  'creampie', 'trombone', '55555555', 'mongoose', 'tottenha', 'butterfl', 'clifford', 'fuckyou2',
  'infantry', 'skywalke', 'raistlin', 'vanhalen', 'sherlock', 'dietcoke', 'ultimate', 'superfly',
  'freedom1', 'drpepper', 'lesbians', 'musicman', 'warcraft', 'microsoft', 'morrison', 'isabelle',
  'thuglife', 'stonecol', 'logitech', 'florence', '1passwor', 'bluemoon', '22222222', 'stardust',
  'margaret', '66666666', '66668888', 'charlott', 'waterloo', '11223344', 'standard', 'alexandr',
  'hannibal', 'frontier', 'welcome1', 'spanking', 'japanese', 'kristina', 'deepthroat', 'bonehead',
  'showtime', 'squirrel', 'mustangs', 'septembe', 'leonardo', 'makaveli', 'vacation', 'passwor1',
  'columbia', 'napoleon', 'motorola', 'william1', 'matthew1', 'robinson', 'penguins', '8j4ye3uz',
  'californ', 'qwertyuiop', 'portland', 'asdfghjkl', 'overlord', 'stranger', 'socrates', 'spiderman',
  '13131313', 'national', 'intrepid', 'megadeth', 'bigballs', 'chargers', 'discover', 'isabella',
  'megapass', 'grateful', 'mushroom', 'cristina', 'hongkong', 'basketball', 'satan666', 'kingkong',
  'penelope', 'thompson', 'anything', 'knickers', 'playtime', 'lightnin', 'slapshot', 'titleist',
  'werewolf', 'fernando', 'blackcat', 'tacobell', 'kittycat', 'thunder1', 'thankyou', 'scoobydo',
  'coltrane', 'lonestar', 'heather1', 'beefcake', 'zzzzzzzz', 'personal', 'anthony1', 'fuckface',
  'lowrider', 'punkrock', 'dodgeram', 'dingdong', 'qqqqqqqq', 'johnjohn', 'asshole1', 'crusader',
  'syracuse', 'meridian', 'turkey50', 'keyboard', 'ilovesex', 'blackman', 'richmond', 'sandiego',
  'cooldude', 'mariners', 'caliente', 'fletcher', 'porsche9', 'kangaroo', 'springer', 'goodtime',
  'chelsea1', 'freckles', 'nebraska', 'webmaster', 'blueeyes', 'director', 'monopoly', 'blackjac',
  'southern', 'peterpan', 'fuckyou1', 'a1b2c3d4', 'sentinel', 'richard1', '1234abcd', 'guardian',
  'candyman', 'mandingo', 'munchkin', 'billyboy', 'rootbeer', 'assassin', 'frederic', 'giovanni',
  'scarlett', 'achilles', 'warriors', 'plymouth', 'cameltoe', 'fuckfuck', 'sithlord', 'backdoor',
  'chevrole', 'lorraine', 'cosworth', 'eternity', 'verbatim', 'chocolate', 'deadhead', 'pineappl',
  'rosemary', 'porkchop', 'blackdog', 'alexander', 'valhalla', 'santiago', 'portugal', '1qazxsw2',
  'stripper', 'sebastia', 'hurrican', '1x2zkg8w', 'atlantic', 'hyperion', '44444444', 'skittles',
  'hastings', 'gangbang', 'sailboat', 'immortal', 'maryland', 'columbus', 'beautiful', 'swordfish',
  'ncc1701a', 'spartans', 'threesom', 'dilligaf', 'pinkfloy', 'catalina', 'formula1', 'scooter1',
  'colombia', 'lancelot', 'angelica', 'rockhard', 'poontang', 'starship', 'starbuck', 'catherin',
  'kentucky', '33333333', '12344321', 'sapphire', 'raiders1', 'excalibu', 'imperial', 'phillips',
  'golfball', 'front242', 'macdaddy', 'qwer1234', 'cowboys1', 'dannyboy', 'martinez', 'aquarius',
  'pppppppp', 'clarence', 'eatpussy', 'beatrice', 'phillies', 'research', 'gggggggg', 'doughboy',
  'lollipop', 'qazwsxed', 'crazybab', 'brothers', 'butthole', 'rightnow', 'greatone', 'gateway1',
  'wildfire', 'jackson1', '0.0.0.000', 'snuggles', 'phoenix1', 'technics', 'gesperrt', 'brucelee',
  'woofwoof', 'theodore', 'richards', 'punisher', 'username', 'bunghole', 'elizabeth', 'lifetime',
  'masterbate', 'diamond1', 'abnormal', 'davidson', 'starfish', 'penetration', 'michaela',
  'caligula', 'railroad', 'bradford', 'military', 'bearbear', 'patrick1', 'christine', 'swinging',
  'labrador', 'justdoit', 'meatball', 'saturday', 'defender', 'piercing', 'microsof', 'mechanic',
  'robotech', 'universe', 'newpass6', 'hellyeah', 'zaq12wsx', 'spectrum', 'jjjjjjjj', 'oklahoma',
  'mmmmmmmm', 'blueblue', 'wolverine', 'sniffing', 'keystone', 'bbbbbbbb', 'handsome', 'tttttttt',
  'ssssssss', 'somethin', 'melissa1', 'marcius2', 'godsmack', 'rangers1', 'deeznuts', 'kingston',
  'yosemite', 'tommyboy', 'masterbating', 'marianne', 'happyday', 'manchest', 'unbelievable',
  'aberdeen', 'nathalie', 'intercourse', 'supersta', 'bcfields', 'hardrock', 'children', 'commando',
  'sinclair', 'squerting', 'jeanette', 'meathead', 'gandalf1', 'magnolia', 'kenworth', 'redalert',
  'homemade', 'webmaste', 'insertion', 'temptress', 'gretchen', 'celebrity', 'ragnarok', 'trinidad',
  'kingfish', 'blackhaw', 'thursday', 'meatloaf', 'interacial', 'streaming', 'pertinant', 'pool6123',
  'animated', 'gordon24', 'fantasies', 'touching', 'homepage', 'ejaculation', 'whocares', 'jamesbon',
  'amsterda', 'february', 'luckydog', 'businessbabe', 'brandon1', 'experience', 'software',
  'rasputin', 'greenbay', 'pa55word', 'contortionist', 'sneakers', 'sonyfuck',
  'test1234', 'roadkill', 'cheerleaers', 'madeline', 'christian', 'brighton', 'housewifes',
  'emmanuel', 'bigmoney', 'seductive', 'sexygirl', 'canadian', 'gangbanged', 'crawford', 'hotpussy',
  'implants', 'intruder', 'andyod22', 'barcelon', 'chainsaw', 'chickens', 'downtown', 'magicman',
  'clevelan', 'designer', 'budweise', 'experienced', 'pitchers', 'passwords', 'jeremiah', 'alliance',
  'halflife', 'saratoga', 'positive', 'transexual', 'close-up', 'sunnyday', 'starfire', 'pictuers',
  'testing1', 'tiberius', 'lisalisa', 'golfgolf', 'flounder', 'majestic', 'trailers', 'mikemike',
  'whitesox', 'angelina', 'goodluck', 'charlton', 'fingerig', 'gallaries', 'lockerroom', 'treasure',
  'absolutely', 'homepage-', 'beerbeer', 'testerer', 'fordf150', 'pa55w0rd', 'kamikaze', 'japanees',
  'masterbaiting', 'callaway', 'panasoni', 'housewife', '18436572', 'sullivan', 'terrapin',
  'masturbation', 'hardcock', 'freeporn', 'pornographic', 'traveler', 'moneyman', 'shopping',
  'thumbnils', 'amateurs', 'apollo13', 'goldwing', 'doghouse', 'pounding', 'truelove', 'underdog',
  'wrestlin', 'sherwood', 'johannes', 'balloons', 'happy123', 'flamingo', 'paintbal', 'llllllll',
  'twilight', 'christie', 'bullseye', 'knickerless', 'binladen', 'peterson', 'thanatos', 'albatros',
  'getsdown', 'nwo4life', 'underwear', 'dddddddd', 'deeznutz', 'enterprise', 'misfit99', 'solution',
  'meredith', 'barefoot', '50spanks', 'scandinavian', 'original', 'shannon1', 'techniques',
  'chemical', 'salvador', 'manchester', 'buckshot', 'thegreat', 'goldstar', 'triangle', 'kristine',
  'snowboar', 'penetrating', 'roadking', 'rockford', 'chicago1', 'ferrari1', 'galeries', 'godfathe',
  'gargoyle', 'gangster', 'pussyman', 'pooppoop', 'newcastl', 'mortgage', 'snoopdog', 'assholes',
  'property', 'broadway', 'butterfly', 'earthlink', 'westwood', 'blackbir', 'slippery', 'pianoman',
  'tomorrow', 'roadrunn', 'attitude', 'seahawks', 'tunafish', 'cinnamon', 'northern', '23232323',
  'zerocool', 'limewire', 'films+pic+galeries', 'francois', 'fuckthis', 'girfriend', 'uncencored',
  'chrisbln', 'netscape', 'hhhhhhhh', 'knockers', 'tazmania', 'pharmacy', 'arsenal1', 'anaconda',
  'australi', 'gotohell', 'bulldog1', 'monalisa', 'whiteout', 'james007', 'bitchass', 'southpar',
  'lionking', 'megatron', 'hawaiian', 'gymnastic', 'panther1', 'wp2003wp', 'passwort', 'friendly',
  'oooooooo', 'bullfrog', 'holyshit', 'jasmine1', 'sergeant', 'babyblue', 'pass1234', 'poseidon',
  'confused', 'hollywood', 'insertions', 'juliette', 'hayabusa', 'hawkeyes', 'geoffrey', 'chuckles',
  'hounddog', 'philippe', 'thunderb', 'marino13', 'handyman', 'cerberus', 'gamecock', 'magician',
  'preacher', 'chrysler', 'contains', 'hedgehog', 'hoosiers', 'dutchess', 'wareagle', 'ihateyou',
  'sunflowe', 'senators', 'terminal', 'laurence', 'maradona', 'america1', 'chicken1', 'passpass',
  'r2d2c3po', 'myxworld', 'missouri', 'wishbone', 'infiniti', 'wonderboy', 'stanford', 'smeghead',
  'titanium', 'charlene', 'fishing1', 'fullmoon', 'absolute', 'seinfeld', 'pingpong', 'matthews',
  'recovery', 'babyface', 'gladiato', 'paranoid', 'packers1', 'longjohn', 'clarinet', 'mortimer',
  'modelsne', 'vladimir', 'together', 'avalanch', '55bgates', 'cccccccc', 'paradigm', 'operator',
  'valencia', 'cocksuck', 'creature', 'borussia', 'browning', 'heritage', 'millions', 'starcraf',
  'spaceman', 'chester1', 'rrrrrrrr', 'sandwich', 'magazine', 'buttfuck', 'yeahbaby', '11235813',
  'bangbang', 'charles1', 'ffffffff', 'doberman', 'overkill', 'claymore', 'brewster', 'electron',
  'eastside', 'minimoni', 'wildbill', 'wildcard', 'yyyyyyyy', 'sweetnes', 'skywalker', 'alphabet',
  'babybaby', 'graphics', 'florida1', 'flexible', 'fuckinside', 'ursitesux', 'christma', 'wwwwwwww',
  'just4fun', 'rebecca1', 'adrienne', '19691969', 'silverad', 'rhiannon', '10101010', 'ashleigh',
  'qwerasdf', 'presiden', 'newyork1', 'brigitte', 'buddyboy', 'heineken', 'millwall', 'beautifu',
  'sinister', 'smashing', 'teddybea', 'ticklish', 'lipstick', 'reynolds', 'applepie', 'digital1',
  'dinosaur', 'icehouse', 'insanity', 'bluefish', 'strength', 'sentnece', 'temppass', 'medicine',
  'hahahaha', 'casanova', 'fountain', 'dolphin1', 'porsche1', 'vampires', 'highheel', 'kkkkkkkk',
  'illinois', '21212121', 'stonecold', 'testpass', 'jiggaman', 'federico', 'scorpio1', 'rt6ytere',
  'madison1', 'coolness', 'christina', 'coldbeer', 'brittney', 'washingt', 'stephanie', 'shepherd',
  'tiffany1', 'mephisto', 'dragonba', 'nygiants', 'password2', 'corleone', 'kittykat', 'vikings1',
  'splinter', 'pipeline', 'meowmeow', 'chestnut', 'longdong', 'quant4307s', 'eastwood', 'moonligh',
  'illusion',
]
