-- Migration 013: pitch_analysis table
-- Stores structured AI coaching summaries + biomechanical analysis per clip.
-- philosophies_applied: array of philosophy IDs that were active and evaluated.
-- biomechanics: free-form jsonb for any structured mechanical observations.
-- event_frames: optional frame indices for key events (foot_contact, release, etc.)

CREATE TABLE IF NOT EXISTS pitch_analysis (
  id                    uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  clip_id               uuid        NOT NULL REFERENCES clips(id) ON DELETE CASCADE,
  player_id             uuid        NOT NULL,
  coach_id              uuid,
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now(),

  -- Rapsodo / TrackMan snapshot at time of analysis
  metrics               jsonb       NOT NULL DEFAULT '{}',

  -- Structured biomechanical observations keyed by category
  -- e.g. { "lower_half": "Good hip drive, back foot staying connected",
  --         "arm_action": "Scap load timing slightly early", ... }
  biomechanics          jsonb       NOT NULL DEFAULT '{}',

  -- Key frame indices detected or manually tagged
  -- e.g. { "peak_leg_lift": 12, "foot_contact": 42, "release": 58, "follow_through": 74 }
  event_frames          jsonb       NOT NULL DEFAULT '{}',

  -- Array of philosophy IDs from philosophies.ts that were evaluated
  philosophies_applied  jsonb       NOT NULL DEFAULT '[]',

  -- Free-text coaching summary generated by AI
  coaching_summary      text,

  -- Prioritized list of action items
  action_items          text[]      NOT NULL DEFAULT '{}',

  -- 0.0–1.0 confidence score for the AI's analysis (null = not computed)
  confidence_score      numeric(4,3),

  -- Inferred or confirmed player attributes at time of analysis
  handedness            text        CHECK (handedness IN ('RHP', 'LHP', 'RHH', 'LHH')),
  age_group             text,
  position              text
);

CREATE INDEX IF NOT EXISTS pitch_analysis_clip_id_idx    ON pitch_analysis(clip_id);
CREATE INDEX IF NOT EXISTS pitch_analysis_player_id_idx  ON pitch_analysis(player_id);
CREATE INDEX IF NOT EXISTS pitch_analysis_created_at_idx ON pitch_analysis(created_at DESC);

-- RLS: coaches can read/write; players can only read their own
ALTER TABLE pitch_analysis ENABLE ROW LEVEL SECURITY;

CREATE POLICY "coaches_all_pitch_analysis" ON pitch_analysis
  FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
        AND profiles.role = 'coach'
    )
  );

CREATE POLICY "players_read_own_pitch_analysis" ON pitch_analysis
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM players
      WHERE players.user_id = auth.uid()
        AND players.id = pitch_analysis.player_id
    )
  );

NOTIFY pgrst, 'reload schema';
